# prettier-ignore
coverage:
  precision: 2
  round: down
  range: 0...100

  status:
    project:
      default:
        target: 0%
    patch:
      default:
        target: 70%

  ignore:
    - "**/mock.ts"
