# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/prognoz_v2_angular

    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      # Lint the source code
      - run:
          name: Linting
          command: npm run lint

      # Build project
      - run:
          name: Building
          command:
            npm run build --prod --aot

      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy:
    working_directory: ~/prognoz_v2_angular

    machine:
      enabled: true
      environment:
        SSH_USER: root
        SSH_ADDRESS: 46.101.159.170
        SSH_PATH: /var/www/tmp-ui

    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:41:74:c6:5e:cf:78:9e:a6:c2:af:39:8a:f1:fd:ca"

      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Deploy over ssh
          command: |
            scp -r ~/prognoz_v2_angular/dist $SSH_USER@SSH_ADDRESS:$SSH_PATH

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
