# prettier-ignore
version: 2

jobs:
  install_dependencies:
    parallelism: 1
    working_directory: ~/prognoz_v2_angular
    docker:
      - image: circleci/node:12-browsers

    steps:
      - checkout

      - restore_cache:
          key: node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run:
          name: install dependencies if no cache
          command: "[ ! -d node_modules ] && npm ci --loglevel warn --yes || echo package.json and package-lock.json unchanged. Using cache."

      - save_cache:
          key: node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    parallelism: 1
    working_directory: ~/prognoz_v2_angular
    docker:
      - image: circleci/node:12-browsers

    steps:
      - attach_workspace:
          at: .

      - run:
          name: test
          command: npm run test

      - run:
          name: upload coverage report
          command: npm run codecov -- --token=$CODECOV_TOKEN

  lint:
    parallelism: 1
    working_directory: ~/prognoz_v2_angular
    docker:
      - image: circleci/node:12-browsers

    steps:
      - attach_workspace:
          at: .

      # - run: npm run lint
      - run: echo "lint is temparary disabled untill all files will be modified according to new linter rules"

  build:
    parallelism: 1
    working_directory: ~/prognoz_v2_angular
    docker:
      - image: circleci/node:12-browsers

    steps:
      - attach_workspace:
          at: .

      - run:
          name: build
          command: npm run build -- --configuration=production --aot

      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    parallelism: 1
    working_directory: ~/prognoz_v2_angular
    docker:
      - image: circleci/node:12-browsers

    steps:
      - add_ssh_keys:
          fingerprints:
            - 'bc:41:74:c6:5e:cf:78:9e:a6:c2:af:39:8a:f1:fd:ca'

      - attach_workspace:
          at: .

      - run:
          name: deploy
          command:  bash ./scripts/deploy.sh

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only: master
