version: 2

jobs:
   install_dependencies:
      parallelism: 1
      working_directory: ~/prognoz_v2_angular
      docker:
         - image: circleci/node:10-browsers

      steps:
         - checkout

         - restore_cache:
              key: node-modules-{{ arch }}-{{ checksum "package-lock.json" }}

         - run:
              command: npm ci

         - save_cache:
              key: node-modules-{{ arch }}-{{ checksum "package-lock.json" }}
              paths:
                 - node_modules

         - persist_to_workspace:
              root: .
              paths:
                 - .

   lint:
      parallelism: 1
      working_directory: ~/prognoz_v2_angular
      docker:
         - image: circleci/node:10-browsers

      steps:
         - attach_workspace:
              at: .

         # - run: npm run lint
         - run: echo "lint is temparary disabled untill all files will be modified according to new linter rules"

   build:
      parallelism: 1
      working_directory: ~/prognoz_v2_angular
      docker:
         - image: circleci/node:10-browsers

      steps:
         - attach_workspace:
              at: .

         - run:
              name: build
              command: npm run build -- --configuration=production --aot

         - save_cache:
              key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
              paths:
                 - dist

   deploy:
      working_directory: ~/prognoz_v2_angular

      machine:
         enabled: true

      steps:
         # add fingerprint from circle-ci site
         - add_ssh_keys:
              fingerprints:
                 - 'bc:41:74:c6:5e:cf:78:9e:a6:c2:af:39:8a:f1:fd:ca'

         # restore data from build job
         - restore_cache:
              key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

         # copy files via scp
         - run:
              name: Deploy over ssh
              command: |
                 scp -r ~/prognoz_v2_angular/dist root@46.101.159.170:/var/www/tmp-ui

         # change rights and move to proper folder
         - run:
              name: Change rights and move to files
              command: |
                 ssh root@46.101.159.170 'sudo chown -R root:www-data /var/www/tmp-ui/ && rm -rf /var/www/ui/dist && mv /var/www/tmp-ui/dist/ /var/www/ui/dist/'

workflows:
   version: 2

   build-and-deploy:
      jobs:
         - install_dependencies
         - lint:
              requires:
                 - install_dependencies
         - build:
              requires:
                 - install_dependencies
         - deploy:
              requires:
                 - build
              filters:
                 branches:
                    only: master
